[Fix] for #160
RoboCup-Humanoid-TC/GameController pull request #163
Opened 2021-06-16 18:59 UTC by MaikePaetzel

There were two problems in the code:
(1) During game interruptions, the secondary clock was sometimes jumping. This is fixed by making the readLock a writeLock (since that thread is actually writing the data object when it updates the time.
(2) During game interruptions, the main time was jumping between two states. This seems to be caused by a weird way of calculating the remaining game time. During game-interruptions, the game duration was not the half-time-length but the remaining game time, which, to me, doesn't make any sense. The same was done for timeouts, which again doesn't make any sense to me. This fixes the bug and as far as I can see it doesn't create any new weird behavior.

2021-06-16 19:55 UTC, medrimonia requested changes
The first part sound sane, the second part is quite blurry.

My contribution to this code was a simple refactoring and I just made code simpler by using inheritance for the GameInterruptions, but I don't think I had any understanding on whether the code was right or wrong for the line I changed here.

What I can get as a starting point to understand what was done there is the previous commit that used this weird 'secsRemaining' as duration:

  - 2019-04-13: medrimonia 8ae36e70
  - 2017-03-25: Kessler df3722a1
  - 2017-03-24: Kessler 4a9790b2
  - 2014-02-23: Sebastian Koralewski f565d9a2
  
  The three previous commits are pretty massive and have not a focus on this specific point. So it would not seem surprising to me that we had a bug like this for many years but that it wasn't properly spotted/reproduced.
  
  In any case, I would just request to remove the commented code, because the code is already cryptic enough without this ^^

2021-06-16 20:34 UTC, MaikePaetzel commented
Agreed, commented code was removed.

2021-06-16 20:59 UTC, medrimonia approved these changes

2021-06-17 07:07 UTC, sheepsy90 approved these changes

2021-06-17 07:38 UTC, merged